# **Load 'train.csv'**
train.csv 的資料為 12 個月中，每個月取 20 天，每天 24 小時的資料(每小時資料有 24 個 features)。

In [1]:
import sys
import pandas as pd
import numpy as np

# !gdown --id '1wNKAxQ29G15kgpBy_asjTcZRRgmsCZRm' --output data.zip
# !unzip data.zip 

data = pd.read_csv('./train.csv', encoding = 'big5')

In [2]:
data.head()

日期  測站        測項     0     1     2     3     4     5     6  ...  \
0  2014/1/1  豐原  AMB_TEMP    14    14    14    13    12    12    12  ...   
1  2014/1/1  豐原       CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2  2014/1/1  豐原        CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  ...   
3  2014/1/1  豐原      NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  ...   
4  2014/1/1  豐原        NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9  ...   

     14    15    16    17    18    19    20    21    22    23  
0    22    22    21    19    17    16    15    15    15    15  
1   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2  0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3   0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4   2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  

[5 rows x 27 columns]

In [3]:
data[data["日期"]=="2014/1/1"]
# 18每天有個feature

日期  測站          測項     0     1     2     3     4     5     6  ...  \
0   2014/1/1  豐原    AMB_TEMP    14    14    14    13    12    12    12  ...   
1   2014/1/1  豐原         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...   
2   2014/1/1  豐原          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37  ...   
3   2014/1/1  豐原        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1  ...   
4   2014/1/1  豐原          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9  ...   
5   2014/1/1  豐原         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9  ...   
6   2014/1/1  豐原         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8  ...   
7   2014/1/1  豐原          O3    16    30    27    23    24    28    24  ...   
8   2014/1/1  豐原        PM10    56    50    48    35    25    12     4  ...   
9   2014/1/1  豐原       PM2.5    26    39    36    35    31    28    25  ...   
10  2014/1/1  豐原    RAINFALL    NR    NR    NR    NR    NR    NR    NR  ...   
11  2014/1/1  豐原          RH    77    68    67    74    72    73    74  ...   
12  2014/1/1  豐原         SO2   1.8     2   1.7   1.6   1.9   1.4   1.5  ...   
13  2014/1/1  豐原         THC     2     2     2   1.9   1.9   1.8   1.9  ...   
14  2014/1/1  豐原       WD_HR    37    80    57    76   110   106   101  ...   
15  2014/1/1  豐原  WIND_DIREC    35    79   2.4    55    94   116   106  ...   
16  2014/1/1  豐原  WIND_SPEED   1.4   1.8     1   0.6   1.7   2.5   2.5  ...   
17  2014/1/1  豐原       WS_HR   0.5   0.9   0.6   0.3   0.6   1.9     2  ...   

      14    15    16    17    18    19    20    21    22    23  
0     22    22    21    19    17    16    15    15    15    15  
1    1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2   0.37  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3    0.1  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4    2.5   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  
5     11    11    22    28    19    12   8.1     7   6.9     6  
6     14    13    25    30    21    13   9.7   8.6   8.7   7.5  
7     65    64    51    34    33    34    37    38    38    36  
8     52    51    66    85    85    63    46    36    42    42  
9     36    45    42    49    45    44    41    30    24    13  
10    NR    NR    NR    NR    NR    NR    NR    NR    NR    NR  
11    47    49    56    67    72    69    70    70    70    69  
12   3.9   4.4   9.9   5.1   3.4   2.3     2   1.9   1.9   1.9  
13   1.9   1.9   1.9   2.1     2   1.9   1.9   1.9   1.9   1.9  
14   307   304   307   124   118   121   113   112   106   110  
15   313   305   291   124   119   118   114   108   102   111  
16   2.5   2.2   1.4   2.2   2.8     3   2.6   2.7   2.1   2.1  
17   2.1   2.1   1.9     1   2.5   2.5   2.8   2.6   2.4   2.3  

[18 rows x 27 columns]

# **Preprocessing** 
取需要的數值部分，將 'RAINFALL' 欄位全部補 0。
另外，如果要在 colab 重覆這段程式碼的執行，請從頭開始執行(把上面的都重新跑一次)，以避免跑出不是自己要的結果（若自己寫程式不會遇到，但 colab 重複跑這段會一直往下取資料。意即第一次取原本資料的第三欄之後的資料，第二次取第一次取的資料掉三欄之後的資料，...）。

In [4]:
data[data["測項"]=="RAINFALL"].head()

日期  測站        測項   0   1   2   3   4   5    6  ...  14  15  16  17  \
10  2014/1/1  豐原  RAINFALL  NR  NR  NR  NR  NR  NR   NR  ...  NR  NR  NR  NR   
28  2014/1/2  豐原  RAINFALL  NR  NR  NR  NR  NR  NR   NR  ...  NR  NR  NR  NR   
46  2014/1/3  豐原  RAINFALL  NR  NR  NR  NR  NR  NR  1.2  ...  NR  NR  NR  NR   
64  2014/1/4  豐原  RAINFALL  NR  NR  NR  NR  NR  NR   NR  ...  NR  NR  NR  NR   
82  2014/1/5  豐原  RAINFALL  NR  NR  NR  NR  NR  NR   NR  ...  NR  NR  NR  NR   

    18  19  20  21  22  23  
10  NR  NR  NR  NR  NR  NR  
28  NR  NR  NR  NR  NR  NR  
46  NR  NR  NR  NR  NR  NR  
64  NR  NR  NR  NR  NR  NR  
82  NR  NR  NR  NR  NR  NR  

[5 rows x 27 columns]

In [5]:
data[data == 'NR'] = 0
data[data["測項"]=="RAINFALL"].head()

日期  測站        測項  0  1  2  3  4  5    6  ... 14 15 16 17 18 19 20  \
10  2014/1/1  豐原  RAINFALL  0  0  0  0  0  0    0  ...  0  0  0  0  0  0  0   
28  2014/1/2  豐原  RAINFALL  0  0  0  0  0  0    0  ...  0  0  0  0  0  0  0   
46  2014/1/3  豐原  RAINFALL  0  0  0  0  0  0  1.2  ...  0  0  0  0  0  0  0   
64  2014/1/4  豐原  RAINFALL  0  0  0  0  0  0    0  ...  0  0  0  0  0  0  0   
82  2014/1/5  豐原  RAINFALL  0  0  0  0  0  0    0  ...  0  0  0  0  0  0  0   

   21 22 23  
10  0  0  0  
28  0  0  0  
46  0  0  0  
64  0  0  0  
82  0  0  0  

[5 rows x 27 columns]

In [6]:
data = data.iloc[:, 3:] # 取需要的數值部分
raw_data = data.to_numpy()

In [7]:
data.columns

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23'],
      dtype='object')

# **Extract Features (1)**
![圖片說明](https://drive.google.com/uc?id=1LyaqD4ojX07oe5oDzPO99l9ts5NRyArH)
![圖片說明](https://drive.google.com/uc?id=1ZroBarcnlsr85gibeqEF-MtY13xJTG47)

將原始 4320 * 18 的資料依照每個月分重組成 12 個 18 (features) * 480 (hours) 的資料。 

In [8]:
raw_data.shape

(4320, 24)

In [9]:
month_data={}
for month in range(12):
    sample = np.empty([18, 24*20]) # 18個features 每個月取 20 天, 每天有24小時
    for day in range(20): # 每個月取 20 天
        sample[:, day * 24 : (day + 1) * 24] = raw_data[18 * (20 * month + day) : 18 * (20 * month + day + 1), :] # 以18個特徵為單位存
    month_data[month] = sample

# **Extract Features (2)**
![alt text](https://drive.google.com/uc?id=1wKoPuaRHoX682LMiBgIoOP4PDyNKsJLK)
![alt text](https://drive.google.com/uc?id=1FRWWiXQ-Qh0i9tyx0LiugHYF_xDdkhLN)

每個月會有 480hrs，每 9 小時形成一個 data，每個月會有 471 個 data，故總資料數為 471 * 12 筆，而每筆 data 有 9 * 18 的 features (一小時 18 個 features * 9 小時)。

對應的 target 則有 471 * 12 個(第 10 個小時的 PM2.5)

In [10]:
x = np.empty([12 * 471, 18 * 9], dtype = float)
y = np.empty([12 * 471, 1], dtype = float)

In [11]:
for month in range(12):
    for day in range(20):
        # print("day:", day)
        for hour in range(24):
            if day == 19 and hour > 14: continue
            # print("hour:", hour)            
            x[month * 471 + day * 24 + hour, :] = month_data[month][:,day * 24 + hour : day * 24 + hour + 9].reshape(1, -1) #vector dim:18*9 (9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9 9)
            y[month * 471 + day * 24 + hour, 0] = month_data[month][9, day * 24 + hour + 9] #value
            

In [12]:
print(x)
print(y)

[[14.  14.  14.  ...  2.   2.   0.5]
 [14.  14.  13.  ...  2.   0.5  0.3]
 [14.  13.  12.  ...  0.5  0.3  0.8]
 ...
 [17.  18.  19.  ...  1.1  1.4  1.3]
 [18.  19.  18.  ...  1.4  1.3  1.6]
 [19.  18.  17.  ...  1.3  1.6  1.8]]
[[30.]
 [41.]
 [44.]
 ...
 [17.]
 [24.]
 [29.]]


In [13]:
x.shape

(5652, 162)

In [14]:
y.shape

(5652, 1)

# **Normalize (1)**

In [15]:
from sklearn.preprocessing import StandardScaler

# API
scaler = StandardScaler().fit(x)
norm_x = scaler.transform(x)

# custom
mean_x = np.mean(x, axis = 0) #18 * 9 
std_x = np.std(x, axis = 0) #18 * 9 
for i in range(len(x)): #12 * 471
    for j in range(len(x[0])): #18 * 9 
        if std_x[j] != 0:
            x[i][j] = (x[i][j] - mean_x[j]) / std_x[j]

In [16]:
norm_x

array([[-1.35825331, -1.35883937, -1.359222  , ...,  0.26650729,
         0.2656797 , -1.14082131],
       [-1.35825331, -1.35883937, -1.51819928, ...,  0.26650729,
        -1.13963133, -1.32832904],
       [-1.35825331, -1.51789368, -1.67717656, ..., -1.13923451,
        -1.32700613, -0.85955971],
       ...,
       [-0.88092053, -0.72262212, -0.56433559, ..., -0.57693779,
        -0.29644471, -0.39079039],
       [-0.7218096 , -0.56356781, -0.72331287, ..., -0.29578943,
        -0.39013211, -0.1095288 ],
       [-0.56269867, -0.72262212, -0.88229015, ..., -0.38950555,
        -0.10906991,  0.07797893]])

In [17]:
x

array([[-1.35825331, -1.35883937, -1.359222  , ...,  0.26650729,
         0.2656797 , -1.14082131],
       [-1.35825331, -1.35883937, -1.51819928, ...,  0.26650729,
        -1.13963133, -1.32832904],
       [-1.35825331, -1.51789368, -1.67717656, ..., -1.13923451,
        -1.32700613, -0.85955971],
       ...,
       [-0.88092053, -0.72262212, -0.56433559, ..., -0.57693779,
        -0.29644471, -0.39079039],
       [-0.7218096 , -0.56356781, -0.72331287, ..., -0.29578943,
        -0.39013211, -0.1095288 ],
       [-0.56269867, -0.72262212, -0.88229015, ..., -0.38950555,
        -0.10906991,  0.07797893]])

# **Split Training Data Into "train_set" and "validation_set"**
這部分是針對作業中 report 的第二題、第三題做的簡單示範，以生成比較中用來訓練的 train_set 和不會被放入訓練、只是用來驗證的 validation_set。

In [18]:
from sklearn.model_selection import train_test_split

x_train_set, x_validation = train_test_split(x, random_state=0, train_size=0.8)
y_train_set, y_validation = train_test_split(y, random_state=0, train_size=0.8)
print(x_train_set)
print(y_train_set)
print(x_validation)
print(y_validation)
print(len(x_train_set))
print(len(y_train_set))
print(len(x_validation))
print(len(y_validation))

[[ 0.55107783  0.54981237  0.38952809 ... -0.76437003 -0.76488172
  -0.57829812]
 [-0.08536588 -0.08640488 -0.24638103 ...  0.54765565 -0.39013211
  -1.14082131]
 [-0.7218096  -0.72262212 -0.88229015 ... -0.01464107  0.35936711
   0.07797893]
 ...
 [-0.24447681 -0.24545919 -0.40535831 ... -0.67065391 -1.04594393
  -0.57829812]
 [ 1.02841061  1.0269753   1.02543721 ... -0.38950555 -0.95225653
  -1.14082131]
 [ 1.34663247  1.18602961  1.18441449 ...  3.07799088  3.35736398
   3.17185646]]
[[ 9.]
 [ 4.]
 [ 0.]
 ...
 [59.]
 [ 9.]
 [17.]]
[[ 0.71018876  0.86792099  1.02543721 ... -0.20207331 -0.39013211
  -0.57829812]
 [ 0.55107783  0.54981237  0.54850537 ... -0.10835719  0.1719923
  -0.20328266]
 [ 1.5057434   1.50413824  1.66134634 ...  2.04711356  2.13942775
   1.76554849]
 ...
 [-0.88092053 -0.72262212 -0.72331287 ... -1.13923451 -0.95225653
  -0.85955971]
 [ 0.07374504 -0.08640488 -0.24638103 ... -0.29578943 -0.20275731
  -0.20328266]
 [-0.88092053 -0.88167643 -0.88229015 ... -0.951802

In [19]:
# custom
import math
x_train_set = x[: math.floor(len(x) * 0.8), :]
y_train_set = y[: math.floor(len(y) * 0.8), :]
x_validation = x[math.floor(len(x) * 0.8): , :]
y_validation = y[math.floor(len(y) * 0.8): , :]
print(x_train_set)
print(y_train_set)
print(x_validation)
print(y_validation)
print(len(x_train_set))
print(len(y_train_set))
print(len(x_validation))
print(len(y_validation))

[[-1.35825331 -1.35883937 -1.359222   ...  0.26650729  0.2656797
  -1.14082131]
 [-1.35825331 -1.35883937 -1.51819928 ...  0.26650729 -1.13963133
  -1.32832904]
 [-1.35825331 -1.51789368 -1.67717656 ... -1.13923451 -1.32700613
  -0.85955971]
 ...
 [ 0.86929969  0.70886668  0.38952809 ...  1.39110073  0.2656797
  -0.39079039]
 [ 0.71018876  0.39075806  0.07157353 ...  0.26650729 -0.39013211
  -0.39079039]
 [ 0.3919669   0.07264944  0.07157353 ... -0.38950555 -0.39013211
  -0.85955971]]
[[30.]
 [41.]
 [44.]
 ...
 [ 7.]
 [ 5.]
 [14.]]
[[ 0.07374504  0.07264944  0.07157353 ... -0.38950555 -0.85856912
  -0.57829812]
 [ 0.07374504  0.07264944  0.23055081 ... -0.85808615 -0.57750692
   0.54674825]
 [ 0.07374504  0.23170375  0.23055081 ... -0.57693779  0.54674191
  -0.1095288 ]
 ...
 [-0.88092053 -0.72262212 -0.56433559 ... -0.57693779 -0.29644471
  -0.39079039]
 [-0.7218096  -0.56356781 -0.72331287 ... -0.29578943 -0.39013211
  -0.1095288 ]
 [-0.56269867 -0.72262212 -0.88229015 ... -0.3895055

# **Training**
![alt text](https://drive.google.com/uc?id=1xIXvqZ4EGgmxrp7c9r0LOVbcvd4d9H4N)
![alt text](https://drive.google.com/uc?id=1S42g06ON5oJlV2f9RukxawjbE4NpsaB6)
![alt text](https://drive.google.com/uc?id=1BbXu-oPB9EZBHDQ12YCkYqtyAIil3bGj)

(和上圖不同處: 下面的 code 採用 Root Mean Square Error)

因為常數項的存在，所以 dimension (dim) 需要多加一欄；eps 項是避免 adagrad 的分母為 0 而加的極小數值。

每一個 dimension (dim) 會對應到各自的 gradient, weight (w)，透過一次次的 iteration (iter_time) 學習。

In [20]:
learning_rate = 100
eps = 0.0000000001
epoch = 10000
dim = 18 * 9 + 1  # input feature = 18 * 9 prev-hours + 1 bias

In [21]:
w = np.zeros([dim, 1])
w.shape

(163, 1)

In [22]:
x = np.concatenate((np.ones([12 * 471, 1]), x), axis = 1).astype(float) # bias (5652, 1) + x (5652, 162)
adagrad = np.zeros([dim, 1]) # store prev grad
x.shape

(5652, 163)

In [23]:
x.transpose().shape

(163, 5652)

In [24]:
(np.dot(x.transpose(), np.dot(x, w) - y)).shape

(163, 1)

In [25]:
for t in range(epoch):
    loss = np.sqrt(np.sum(np.power(np.dot(x, w) - y, 2))/471/12) #rmse # [(y' - y)^2 / ( x.shape[0] )] ^ 0.5
    if(t%1000==0):
        print(str(t) + ":" + str(loss))
    gradient = 2 * np.dot(x.transpose(), np.dot(x, w) - y)  # grad = 2 * dot( (y' -y), X_T )   #dim*1   # (163, 1)
    adagrad += gradient ** 2                                # ada_pregrad += gra**2
    w = w - learning_rate * gradient / np.sqrt(adagrad + eps)   # w -= lr * grad / sqrt(ada_pregrad) => remove square
np.save('weight.npy', w)

0:27.071214829194115
1000:7.0909686439472175
2000:6.02412917022559
3000:5.786921459274559
4000:5.719646593920436
5000:5.697327465527851
6000:5.6890026614252855
7000:5.685550743411822
8000:5.683950654084061
9000:5.683112196533551


# **Testing**
![alt text](https://drive.google.com/uc?id=1165ETzZyE6HStqKvgR0gKrJwgFLK6-CW)

載入 test data，並且以相似於訓練資料預先處理和特徵萃取的方式處理，使 test data 形成 240 個維度為 18 * 9 + 1 的資料。

In [26]:
testdata = pd.read_csv('./test.csv', header = None, encoding = 'big5')
test_data = testdata.iloc[:, 2:]
test_data[test_data == 'NR'] = 0
testdata.head()

/home/leyan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/leyan/anaconda3/envs/tensorflow/lib/python3.6/site-packages/pandas/core/frame.py:3414: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._where(-key, value, inplace=True)


0         1     2     3     4     5     6     7     8     9     10
0  id_0  AMB_TEMP    21    21    20    20    19    19    19    18    17
1  id_0       CH4   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.7   1.8
2  id_0        CO  0.39  0.36  0.36   0.4  0.53  0.55  0.34  0.31  0.23
3  id_0      NMHC  0.16  0.24  0.22  0.27  0.27  0.26  0.27  0.29   0.1
4  id_0        NO   1.3   1.3   1.3   1.3   1.4   1.6   1.2   1.1   0.9

In [27]:
test_data = test_data.to_numpy()
test_data.shape

(4320, 9)

In [28]:
test_x = np.empty([240, 18*9], dtype = float) # 240 days, 18 features
for i in range(240):
    test_x[i, :] = test_data[18 * i: 18* (i + 1), :].reshape(1, -1)

In [29]:
# API (previous scalar)
norm_test_x = scaler.transform(test_x)
print(norm_test_x)

print("--------------------------------------------------------------")
# custom
for i in range(len(test_x)):
    for j in range(len(test_x[0])):
        if std_x[j] != 0:
            test_x[i][j] = (test_x[i][j] - mean_x[j]) / std_x[j]
print(test_x)

[[-0.24447681 -0.24545919 -0.40535831 ... -0.67065391 -1.04594393
   0.07797893]
 [-1.35825331 -1.51789368 -1.51819928 ...  0.17279117 -0.10906991
  -0.48454426]
 [ 1.5057434   1.34508393  1.50236906 ... -1.32666675 -1.04594393
  -0.57829812]
 ...
 [ 0.3919669   0.54981237  0.70748265 ...  0.26650729 -0.20275731
   1.20302531]
 [-1.8355861  -1.8360023  -1.83615384 ... -1.04551839 -1.13963133
  -1.14082131]
 [-1.35825331 -1.35883937 -1.359222   ...  2.98427476  3.26367657
   1.76554849]]
--------------------------------------------------------------
[[-0.24447681 -0.24545919 -0.40535831 ... -0.67065391 -1.04594393
   0.07797893]
 [-1.35825331 -1.51789368 -1.51819928 ...  0.17279117 -0.10906991
  -0.48454426]
 [ 1.5057434   1.34508393  1.50236906 ... -1.32666675 -1.04594393
  -0.57829812]
 ...
 [ 0.3919669   0.54981237  0.70748265 ...  0.26650729 -0.20275731
   1.20302531]
 [-1.8355861  -1.8360023  -1.83615384 ... -1.04551839 -1.13963133
  -1.14082131]
 [-1.35825331 -1.35883937 -1.359222

In [30]:
test_x = np.concatenate((np.ones([240, 1]), test_x), axis = 1).astype(float) # concate bias
test_x.shape

(240, 163)

# **Prediction**
說明圖同上

![alt text](https://drive.google.com/uc?id=1165ETzZyE6HStqKvgR0gKrJwgFLK6-CW)

有了 weight 和測試資料即可預測 target。

In [31]:
w = np.load('weight.npy')
ans_y = np.dot(test_x, w) # ans = f(test_x)
ans_y.shape

(240, 1)

# **Save Prediction to CSV File**

In [32]:
# simple
dtypes = np.dtype(
    [
        ("id", str),
        ("value", int)       
    ]
)
submit_file = pd.DataFrame(np.empty(0, dtype=dtypes))

for i in range(240):
    row = {'id': 'id_' + str(i), "value" : ans_y[i][0] }
    submit_file = submit_file.append(row, ignore_index=True)
submit_file.to_csv('submit.csv', index=False)

In [33]:
submit_file.head()

id      value
0  id_0   6.680817
1  id_1  18.175043
2  id_2  23.418748
3  id_3   7.718373
4  id_4  27.034572

In [34]:
len(submit_file.index)

240

In [35]:
# For big save data
import csv
with open('submit.csv', mode='w', newline='') as submit_file:
    csv_writer = csv.writer(submit_file)
    header = ['id', 'value']
    print(header)
    csv_writer.writerow(header)
    for i in range(240):
        row = ['id_' + str(i), ans_y[i][0]]
        csv_writer.writerow(row)
        print(row)

['id', 'value']
['id_0', 6.68081651316399]
['id_1', 18.175042958359807]
['id_2', 23.41874814626689]
['id_3', 7.718372911343295]
['id_4', 27.034571791813224]
['id_5', 22.248853156964735]
['id_6', 23.84486228740568]
['id_7', 30.460335930669395]
['id_8', 16.859794092616454]
['id_9', 59.68548560443345]
['id_10', 11.678653765482155]
['id_11', 9.339111386720147]
['id_12', 63.43871399049273]
['id_13', 53.23668623424851]
['id_14', 22.198433126132784]
['id_15', 12.162145428580796]
['id_16', 32.49195647327168]
['id_17', 66.67425388005489]
['id_18', -0.4187691332887875]
['id_19', 17.16149290099828]
['id_20', 41.699698195290004]
['id_21', 72.09611187087397]
['id_22', 9.370373636439414]
['id_23', 17.733537532456022]
['id_24', 14.756262623023042]
['id_25', 37.64756218274098]
['id_26', 14.607239932847744]
['id_27', 69.93385286212623]
['id_28', 7.260237456733265]
['id_29', 55.42716919716853]
['id_30', 24.440041872449825]
['id_31', 8.478487779920899]
['id_32', 2.508198851311702]
['id_33', 18.7342124434